sonar.projectKey=home-duy-downloads-project1-road-finder
sonar.projectName=Project1-Road-Finder
sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8
sonar.sources=backend/app,frontend/src,api
sonar.tests=backend/tests
sonar.test.inclusions=backend/tests/**
sonar.exclusions=**/node_modules/**,**/.venv/**,**/venv/**,**/__pycache__/**,**/dist/**,**/build/**,**/coverage/**,**/.next/**,**/*.tsbuildinfo,**/.git/**,**/*.pyc
sonar.python.version=3
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.coverage.exclusions=frontend/src/**
sonar.javascript.node.maxspace=4096
